### ISSUE TITLE
[FEATURE] allow opening gist in browser directly

### ISSUE THREAD

**Issue by ctf0** [kenhowardpdx/vscode-gist#113]
**This is a**

- [ ] bug report
- [x] feature request

#### Description
atm in order to open a gist in the browser it have to first be opened in the editor, but the expected behavior would be opening directly in browser.

**Comment by kenhowardpdx** [comment]
Thank you for the feature request. I will look into doing this.

**Comment by ctf0** [comment]
hi again, i managed to add the logic needed to get this option working but i cant either test it with debug or create a vsx to install it.

r u ok to send u a PR with that ?
