### ISSUE TITLE
Open Gist not showing list of code snippets

### ISSUE THREAD

**Issue by SheepDomination** [kenhowardpdx/vscode-gist#114]
I have a gist on github, although when starting `GIST:Open Gist` followed by typing the name of my gist, I do not get a list of all the gists code snippets ?

**Comment by kenhowardpdx** [comment]
Do you see anything after selecting `GIST: Open Gist`? An error? Gists that don't belong to you?

**Comment by SheepDomination** [comment]
I don't see anything when selecting `GIST:Open Gist`, including no errors or any Gists that don't belong to me ?

**Comment by SheepDomination** [comment]
Has Gist changed, as there is no more `GIST:Open Gist` option ?

**Comment by kenhowardpdx** [comment]
It's definitely still a feature. Do you still have the extension installed?
https://github.com/kenhowardpdx/vscode-gist/blob/develop/README.md#openedit-gists

**Comment by SheepDomination** [comment]
It appears I accidentally removed the extension, although after re-installing the issue I had originally is resolved. 
The problem is, the extension only works on github, instead of self-hosted git sites.

**Comment by kenhowardpdx** [comment]
The extension does work w/ GitHub Enterprise. Please create a new issue with as much details as possible re: GitHub Enterprise.
