### ISSUE TITLE
BUG - GIST: Add File uploads a file with only one word "subfolder" when my file name ends with the substring "(output subfolder).py"

### ISSUE THREAD

**Issue by 2jacobtan** [kenhowardpdx/vscode-gist#115]
**This is a**

- [ x ] bug report
- [ ] feature request

#### Description

Gist 3.0.3

**VS Code**
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

(copy-paste from title)
BUG - GIST: Add File uploads a file with only one word "subfolder" when my file name ends with the substring "(output subfolder).py"

Sorry I'm busy now and hope this helps!

**Comment by kenhowardpdx** [comment]
Thank you for the bug report! :)

**Comment by 2jacobtan** [comment]
Thank you for the extension :)

**Comment by kenhowardpdx** [comment]
I'm unable to reproduce. Is this still an issue?

**Comment by 2jacobtan** [comment]
I've just tested too. Also cannot repro.

Wow it's been 2 years :D
