### ISSUE TITLE
How do I delete Gist profile

### ISSUE THREAD

**Issue by jamongK** [kenhowardpdx/vscode-gist#120]
**This is a**

- [ ] bug report
- [ ] feature request

#### Description

**I accidentally created 2 profiles of Gist on VSCODE
I want to delete one of them.
Is there any way I can delete it?**

**Comment by kenhowardpdx** [comment]
You can reset the state which will remove all profiles: ctrl+shift+0

https://github.com/kenhowardpdx/vscode-gist#all-commands--keyboard-mappings

**Comment by MateoRodriguez0** [comment]
> You can reset the state which will remove all profiles: ctrl+shift+0
> 
> https://github.com/kenhowardpdx/vscode-gist#all-commands--keyboard-mappings

That's not forking
