### ISSUE TITLE
FEATURE - Add Security Policy and improve contributor docs and readme.

### ISSUE THREAD

**Issue by asears** [kenhowardpdx/vscode-gist#121]
**This is a**
- [ ] bug report
- [x] feature request

#### Description
https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository

I'll send over a pull request in case it's useful, thanks for quickly answering my questions about the extension on Twitter!

**Comment by kenhowardpdx** [comment]
Thanks for the PR. Sorry for the delayed reply. We can discuss this in the PR. :)

**Comment by kenhowardpdx** [comment]
Closing. Won't add a security policy.
