### ISSUE TITLE
README needs more information

### ISSUE THREAD

**Issue by fayimora** [kenhowardpdx/vscode-gist#123]
**This is a**

- [x] bug report
- [ ] feature request

#### Description
Hi, 

Can someone pls add a full sample for `profileOptions` to the readme?

The readme says
> profileOptions gives you some debugging capabilities. You can provide a profile name along with key, url, and rejectUnauthorized values. Before you can use profileOptions you *MUST* have the profile created.

To be honest, I have no clue what this all means. 

- What debugging capabilities for a gist? 
- What's a profile name?
- Where do I get this URL?
- Is the key the token from Github?
- What about 2FA? Will I need something to configure that
- e.t.c

I think that statement comes with the expectation that you're a VSC sensei. All most people really want to know (myself inclusive) is what to add to their `settings.json` to get this all working but it's not so clear from the readme(I've asked 4 people to help already). It will be great if someone can add some "for dummies" details to the readme. 🤗

Thanks

**Comment by kenhowardpdx** [comment]
I understand. This was a work-around for some users wanting to set the profiles in the `settings.json` it shouldn't be used by regular users. I'll look at adding better documentation for this.

**Comment by kenhowardpdx** [comment]
Not updating README. The documentation holds up.
