### ISSUE TITLE
BUG: Cant create gist from extension ipynb

### ISSUE THREAD

**Issue by tyoc213** [kenhowardpdx/vscode-gist#128]
**This is a**
- [x] feature request

When I try to create a gist with that extension I got:

`vscode-gist>error: extension.gist.create > Open a file before creating`

But I can create other gist like from py files.

**Comment by kenhowardpdx** [comment]
Thank you for filing this bug.

**Comment by kenhowardpdx** [comment]
Is this still an issue? I'm unable to reproduce.

Could you list the steps to reproduce the issue starting from opening VSCode?
