### ISSUE TITLE
FEATURE - New insert favorite gist command

### ISSUE THREAD

**Issue by k-kuroguro** [kenhowardpdx/vscode-gist#142]
**This is a**
- [ ] bug report
- [x] feature request

#### Description
I use gist to manage my snippets, and it would be great if I could insert starred gist as well as my own.

**Comment by kenhowardpdx** [comment]
Would the desired user flow be:

1. `> GIST: Insert Text From Gist File`
2. Select `Personal Gist` or `Starred Gist`
3. Select Gist
4. Select File to insert

**Comment by k-kuroguro** [comment]
The fewer steps, the better, in my opinion.

1. Open file and select the insertion point.
2. `> GIST: Insert Text From Gist File` or `Starred Gist File`
3. Select Gist
