### ISSUE TITLE
keyboard shortcuts problem

### ISSUE THREAD

**Issue by baixiaoyu2997** [kenhowardpdx/vscode-gist#15]
(sorry for my english)

vscode version:1.16.1
system: win10

e.g: alt+o
when i use it ,vscode show me the "there are no entries to pick from"
what i miss?

**Comment by kenhowardpdx** [comment]
Hi @baixiaoyu2997! 

Thank you for your question. The message you are seeing is from vscode when zero items are available in the quick picker. Do you have a gist saved to github? If not, you will see this message.

Please let me know if you need more help and I will try my best.

**Comment by baixiaoyu2997** [comment]
@kenhowardpdx 
open vscode ,first time use shortcut keys,show me the:"GIST ERROR: Cannot read property 'name' of undefined [github]",
And then use the shortcut keys will always show "there are no entries to pick from".

when i use F1 ->GIST open block , it's  work,can show me the gist list

**Comment by kenhowardpdx** [comment]
Can you share which version of the extension you have installed?

**Comment by baixiaoyu2997** [comment]
@kenhowardpdx 
oh, I just found that I was using another gist extension,haha,  now version is 1.1.4,it's work now ,thanks for you time

**Comment by baixiaoyu2997** [comment]
@kenhowardpdx 
oh, I just found that I was using another gist extension,haha, now version is 1.1.4,it's work now ,thanks for your time

**Comment by baixiaoyu2997** [comment]
@kenhowardpdx 
 i very very hope this extension can  add local cace feature,just like evermonkey extension, Will you think about it?

**Comment by kenhowardpdx** [comment]
@baixiaoyu2997 I will look into it. Would you want to create an issue so you can track the progress?

**Comment by baixiaoyu2997** [comment]
@kenhowardpdx     
.......no, because it make me  feel like i push you  to work, doesn't feel good,  Ahhhhh

**Comment by kenhowardpdx** [comment]
¯\_(ツ)_/¯
