### ISSUE TITLE
BUG - GIST: Open Gist shows other people's gist. Fatal!

### ISSUE THREAD

**Issue by codewithleader** [kenhowardpdx/vscode-gist#153]
BUG - GIST: Open Gist shows other people's gist.

**This is a**

- [x ] bug report
- [ ] feature request

#### Description

When I try to open my gists, it shows me other people's gists, it shows me @jonathanapp 's, @parzhitsky 's, and others. It's not good at all, so my gists are showing up to someone else!
This is a fatal error.

VSCode Version: 1.80.2
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:41:52.615Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-50-generic

![Screenshot from 2023-07-28 08-34-53](https://github.com/kenhowardpdx/vscode-gist/assets/62060473/09238bf8-4076-4e93-910d-398ce80a7fb8)

**Comment by parzhitsky** [comment]
I don't think it's a bug.

GitHub gists are of two kinds: public (visible during search) and secret (invisible during search). Secret gists aren't hidden, just not searchable.

**Comment by codewithleader** [comment]
> GitHub gists are of two kinds: public (visible during search) and secret (invisible during search). Secret gists aren't hidden, just not searchable.

But everyone's gist appears except mine, before only my gist appeared.

**Comment by parzhitsky** [comment]
Ah. Then I should be missing something.

**Comment by codewithleader** [comment]
> Ah. Then I should be missing something.

Yes, I tried to modify your gist by adding a small text to test if I could modify your gist but thank God it didn't let me, at least our gist is still safe.
