### ISSUE TITLE
Opening a block/gist causes VSCode to close all unsaved files (possible data loss)

### ISSUE THREAD

**Issue by sveggiani** [kenhowardpdx/vscode-gist#16]
**This is a**
- [X] bug report
- [ ] feature request

#### Description
Opening a block/gist causes VSCode to close all unsaved files **causing data loss**. Only the active file is kept open. 

![ajax_upload](https://user-images.githubusercontent.com/560791/31697796-2a3be8de-b390-11e7-9cf5-b5924d07af38.gif)

**Comment by kenhowardpdx** [comment]
Ouch! Thanks for the heads up.

**Comment by kenhowardpdx** [comment]
@sveggiani I've just put this in the 1.1.5 release https://github.com/kenhowardpdx/vscode-gist/releases/tag/v1.1.5

**Comment by sveggiani** [comment]
@kenhowardpdx thank you very much. Seems to work perfectly now :)
