### ISSUE TITLE
Feature request - Opening a specific file in a block

### ISSUE THREAD

**Issue by eugene2candy** [kenhowardpdx/vscode-gist#20]
**This is a**

- [ ] bug report
- [x] feature request

#### Description
After version 1.1.5, 'open multiple files' issue is fixed. 
But it looks like an explosion if a block contains hundreds of files. 
Only if a block including less than 20 files is acceptable. 
Otherwise it's better to have a chance to open a specific file in a specific block. 
Adding another command `GIST: Open Block File` will be a good idea. (reply for #18)

**Comment by eugene2candy** [comment]
But maybe it's better to combine `GIST: Open Block` and `GIST: Open Block File` into a single command... 
```
if (fileNum < 20)
    just open all files
if (fileNum >= 20)
    show a list and provide options to open all or a specific file: 
    Open All Files
    1. xxx
    2. xxx
    ... 
    111. xxx
```

**Comment by kenhowardpdx** [comment]
Not that I want to slow the users flow, I think this is the right situation for a prompt.

`The selected block contains x number of files. [Open Single File] [Open All]`

The threshold for number of files in block that would trigger this prompt might be configurable... and have a sane default of 10(?).

What do you think @eugene2candy? Would this solution be cumbersome?

**Comment by kenhowardpdx** [comment]
Sorry.. your approach w/ the list of files and "Open All Files" option at the top of the list makes more sense. I totally missed that line.

Anyone is welcome to take a stab at this. :)

**Comment by eugene2candy** [comment]
@kenhowardpdx  
I think combine `GIST: Open Block File` into `GIST: Open Block` make more sense. So we don't need `GIST: Open Block File` anymore. 

And setting a threshold for number of files in a block is necessary because most of users only have a block with 2 or 3 files while a few users have hundreds of files in a single block just like me :D 

So anyone can use command `GIST: Open Block` to open the files. With the threshold existing, users can double check if they want to **open all** or **just a specific file**. 

As you mentioned, threshold default could be 10. This number is much better :)

**Comment by kenhowardpdx** [comment]
This feature has been added in v1.2.0 https://github.com/kenhowardpdx/vscode-gist/compare/v1.1.5...v1.2.0
