### ISSUE TITLE
FEATURE: Support for manually creating API key instead of supplying password

### ISSUE THREAD

**Issue by pzelnip** [kenhowardpdx/vscode-gist#21]
**This is a**
- [ ] bug report
- [x] feature request

#### Description

I *really* don't like the idea of giving my password to a 3rd party extension.  Instead I'd rather manually create the API key for creating gists much like I have to for the Settings Sync extension (https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync), and then just have vscode-gist use that API key.

**Comment by kenhowardpdx** [comment]
Working on it.
![access-token](https://user-images.githubusercontent.com/1892667/34509215-59b544cc-effc-11e7-863a-878de0102448.gif)

**Comment by kenhowardpdx** [comment]
This feature has been added in v1.2.0 https://github.com/kenhowardpdx/vscode-gist/compare/v1.1.5...v1.2.0

**Comment by pzelnip** [comment]
Awesome!  TYVM, works great.
