### ISSUE TITLE
Feature Request - Command for Login With Access Token

### ISSUE THREAD

**Issue by pesimon** [kenhowardpdx/vscode-gist#22]
The git animation shows the `Login With Access Token` but I couldn't find which command is used to set this up.

**Comment by kenhowardpdx** [comment]
@pesimon currently you can only access it if you press enter when leaving the username field blank.

I should add commands for both options. Thanks for your feedback!

**Comment by kenhowardpdx** [comment]
**Here are the steps for setting the token in the UI:**

1. press `F1` on your keyboard to open the command pallette
2. filter for `GIST: Open Block` and press enter on your keyboard when selected
3. when prompted for a username press enter without entering a value
4. you'll be prompted for a personal access token
5. enter personal access token and press enter on your keyboard

**Comment by texastoland** [comment]
I think you could accept either at the initial prompt and react accordingly if it's a 40-digit hex string.

**Comment by texastoland** [comment]
Exactly. I don't feel strongly about it. It just sounds nice relative to a blank field or a separate command. I stumbled on the issue looking for another one.

**Comment by mymartin** [comment]
The prompts that shows in order in Command Palette when you `Create New Block` are:

1. username
2. token
3. description
4. private?

You can press "ESCAPE" and jump to `Login With Access Token`.

**Comment by kenhowardpdx** [comment]
v2.0.0 does not authenticate with username and password anymore. personal access token is the only way to authenticate with this extension.
