### ISSUE TITLE
FEATURE - cater for 2-factor authentication

### ISSUE THREAD

**Issue by barneycarroll** [kenhowardpdx/vscode-gist#23]
**This is a**

- [ ] bug report
- [x] feature request

#### Description

<img width="482" alt="screen shot 2018-01-10 at 14 59 26" src="https://user-images.githubusercontent.com/83627/34779011-e7851dc0-f616-11e7-9814-116af0067fb4.png">

Not sure how I can enable the plugin to perform 2-factor authentication…

**Comment by kenhowardpdx** [comment]
Maybe I should enable 2FA and test this out :)

**Comment by lambdamusic** [comment]
+1 for this feature

**Comment by kenhowardpdx** [comment]
**Here are the steps for setting the token in the UI:**

1. press `F1` on your keyboard to open the command pallette
2. filter for `GIST: Open Block` and press enter on your keyboard when selected
3. when prompted for a username press enter without entering a value
4. you'll be prompted for a personal access token
5. enter personal access token and press enter on your keyboard

**Comment by kenhowardpdx** [comment]
I will not handle 2FA. Only personal access tokens will be used from v2.0.0 and beyond.
