### ISSUE TITLE
Move token storage out of settings

### ISSUE THREAD

**Issue by texastoland** [kenhowardpdx/vscode-gist#25]
**This is a**

- [ ] bug report
- [x] feature request

#### Description

I want to version my editor settings with my public dotfiles but need to elide my token. It looks like [the GitHub extension](https://github.com/KnisterPeter/vscode-github) implements the [platform `Memento` API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Memento) to avoid exposing it. See [`tokens.ts`](https://github.com/KnisterPeter/vscode-github/blob/master/src/tokens.ts) and [`commands/tokens.ts`](https://github.com/KnisterPeter/vscode-github/blob/master/src/commands/token.ts).

**Comment by kenhowardpdx** [comment]
I'm actually storing your token in Memento. The settings file is for legacy users. I could probably pull it since users of this version have always had Memento storage.

**Comment by texastoland** [comment]
I didn't even try it without the setting 🤦🏽‍♂️ Thanks!
