### ISSUE TITLE
BUG - Can't create new blocks or save existing ones

### ISSUE THREAD

**Issue by ramsaylanier** [kenhowardpdx/vscode-gist#26]
**This is a**

- [ x] bug report
- [ ] feature request

#### Description
VS Code: Version 1.20.1 (1.20.1)
Gist Extension: Version 1.2.0

Simply put, I can't create new blocks or save updates to existing ones. I have successfully validated using a Personal Access Token, and I can open existing blocks. I get a  `GIST ERROR: Not Found[github]` error. 

Screenshow below.

![screen shot 2018-02-19 at 5 05 25 pm](https://user-images.githubusercontent.com/2359852/36398874-2913d7fa-1597-11e8-9e28-80fd92224228.png)

**Comment by kenhowardpdx** [comment]
Thanks @ramsaylanier. Are you able to use other commands from the command palette?

**Comment by ramsaylanier** [comment]
Yup. I can open existing ones. I just can't seem to be able to save/create anything.

**Comment by ramsaylanier** [comment]
After forking this repo and playing around with it for an hour, I finally realized that I didnt enable gist creation for my Personal Access Token (DOH!).

Might maybe want to add something to the documentation about that if it comes up again.

**Comment by kenhowardpdx** [comment]
Oh cool! I'm glad you got it working. Yeah, when you login w/ username and password you don't need to worry about it. I'll be sure to update the README.
