### ISSUE TITLE
BUG: token added each login

### ISSUE THREAD

**Issue by rbenson** [kenhowardpdx/vscode-gist#29]
**This is a**

- [x] bug report
- [ ] feature request

#### Description

It looks like every log in, or once daily, a new token is added. I added this ext a few days ago, and looking a few minutes ago, I had 5 or 6 tokens for this ext.

**Comment by kenhowardpdx** [comment]
Can you tell me if the extension is requesting login credentials each time?

**Comment by rbenson** [comment]
Yes it is.

**Comment by kenhowardpdx** [comment]
Ok. It's definitely not supposed to do that. Are you on Windows or Mac? Any other information about your setup you can give me?

**Comment by kenhowardpdx** [comment]
Is this still happening?
