### ISSUE TITLE
URL missing username when creating via token

### ISSUE THREAD

**Issue by Stanzilla** [kenhowardpdx/vscode-gist#32]
**This is a**

- [x] bug report
- [ ] feature request

#### Description

When creating a new gist via the oauth token, the url that is opened in the browser when it is done is missing the username parameter. Maybe add an option to save that to the settings since it is not asked for during the creation flow?

Note: This only happened the first time doing that, every use after the first redirected fine.

**Comment by kenhowardpdx** [comment]
Closing. If this is still an issue please re-open.
