### ISSUE TITLE
Extension Size

### ISSUE THREAD

**Issue by pzelnip** [kenhowardpdx/vscode-gist#33]
**This is a**

- [ ] bug report
- [x] feature request

#### Description
Looking in my ```/Users/<my user name>/.vscode/extensions/``` directory the kenhowardpdx.vscode-gist-1.2.0 directory is (at 268MB of space) more than twice as big as the next largest extension I have installed.  Looking inside that directory there appears to be a ```.vscode-test``` directory which is the bulk of that space that appears to contain a copy of the Visual Studio Code.app directory.

Is this really needed?  This seems rather wasteful.

**Comment by kenhowardpdx** [comment]
Thanks for the report. I'll give this a look.
