### ISSUE TITLE
Changing user

### ISSUE THREAD

**Issue by all4site** [kenhowardpdx/vscode-gist#35]
**This is a**

- [ ] bug report
- [ x] feature request

#### Description

Hello everybody!
I have a question how to change the user. When I enter the username and password from the gihub first time it is remembered forever. How can I change it?

**Comment by kenhowardpdx** [comment]
Good idea.

**Comment by kenhowardpdx** [comment]
v2.0.0 introduces profiles. You can have multiple users/github enterprise accounts.
