### ISSUE TITLE
Could not open or create a block due to errors

### ISSUE THREAD

**Issue by arekuusa** [kenhowardpdx/vscode-gist#40]
Incidentally, I added a block. I could not open and create a block due to errors.
See screenshot http://prntscr.com/k0qzbn
All cleared the cache and removed the extension, installed. Did not help.
What to do? Help me please.

**Comment by kenhowardpdx** [comment]
![image](https://user-images.githubusercontent.com/1892667/42192169-03ab1d46-7e1c-11e8-9a92-4e97ec80039a.png)

**Comment by arekuusa** [comment]
There's an answer? Corrected?

**Comment by kenhowardpdx** [comment]
I've just published v2.0.0 which uses the latest REST library from GitHub. Let me know if you are still experiencing issues.

**Comment by kenhowardpdx** [comment]
Closing.
