### ISSUE TITLE
BUG - vscode-git keeps forgetting my access token and adding a new one

### ISSUE THREAD

**Issue by robertmain** [kenhowardpdx/vscode-gist#41]
**This is a**

- [X] bug report
- [ ] feature request

#### Description
Every time I go to create a new gist, it seems to have always forgotten my access token and keeps having me log in again to GitHub. Possibly related to #29 

**OS:** Windows 10  
**VS Code Version:** 
```
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
**Extension Version:** 1.2.1

Screenshot:  
![image](https://user-images.githubusercontent.com/537684/42406119-949e31a2-816f-11e8-89c8-f712d433b857.png)

**Comment by AntonGrekov** [comment]
I have same issue. 

OS: Windows 10
VS Code Version: 1.28.2
node.js: 8.9.3
arch: x64

I always has to enter access token or username:pass. Also, after entering credentials most of the time nothing happenes

**Comment by kenhowardpdx** [comment]
I just published v2.0.0, please let me know if you are still experiencing this issue.

**Comment by joelcancela** [comment]
@kenhowardpdx I had to recreate a profile (by clicking on GIST in the status bar), but it seems to work now.
I relaunched VSCode to try to replicate the issue and it seems fixed, thanks ! :)

**Comment by kenhowardpdx** [comment]
Great to hear!
