### ISSUE TITLE
BUG vscode-gist not connecting behind proxy

### ISSUE THREAD

**Issue by sergeyfarin** [kenhowardpdx/vscode-gist#42]
Error message when connecting from behind proxy: 

GIST ERROR: request to https://api.github.com/gists?per_page=9999 failed, reason: connect ETIMEDOUT 192.30.253.117:443 [github]

Proxy settings are specified in environment variable, VSCode user settings and by command line arguments. VS Code itself and other extensions do connect to Github and work fine.

**Comment by kenhowardpdx** [comment]
That's interesting. Thanks for the bug report. We are using the @octokit/rest node library for accessing github. Maybe there's a similar bug there... https://www.npmjs.com/package/@octokit/rest

I'll investigate.

**Comment by darktears** [comment]
Same problem for me.

**Comment by kenhowardpdx** [comment]
@sergeyfarin is this still an issue?

**Comment by alexanek** [comment]
Same problem. Can't solve by myself!(

**Comment by kenhowardpdx** [comment]
Can you try using the new `profileOptions` setting and set `rejectUnauthorized` to `false?
https://github.com/kenhowardpdx/vscode-gist#extension-settings

**Comment by kenhowardpdx** [comment]
Closing. If this is still an issue please re-open.

**Comment by sergeyfarin** [comment]
> @sergeyfarin is this still an issue?

Ken @kenhowardpdx , sorry for the delayed reply! Did not work with VS Code for a while!
I just tested and it works behind proxy.
Thank you very much for your great plugin!

Thank you!!!
Kind Regards,
Sergey
