### ISSUE TITLE
FEATURE - Configuration to hide the extension in the status bar

### ISSUE THREAD

**Issue by Logerfo** [kenhowardpdx/vscode-gist#43]
**This is a**
- [ ] bug report
- [x] feature request

#### Description
![image](https://user-images.githubusercontent.com/19306384/45817751-1bb95280-bcb6-11e8-9a3e-c376adc8b89e.png)
Some extensions have a bool configuration to hide itself in the status bar. It would be nice to have in this one, because its content is not very useful, at least for me.
Here's an example of another open source extension which has this configuration: https://github.com/eamodio/vscode-gitlens/blob/4ddb871459a3a1a1e132c8bdf83ac12e3b699649/package.json#L1280
Thanks!

**Comment by kenhowardpdx** [comment]
Agreed. I added that so a user could see which service they were connected to and and give you the ability to click to disconnect. I had hoped I'd get GitHub Enterprise, Bitbucket, and other services added to this extension. 

In conclusion, a boolean would be a nice added feature to turn this off.

**Comment by const-int** [comment]
Please add this option. I like to keep my status bar simple and clean.

**Comment by mlewand** [comment]
Just started cleaning up my status bar too. @kenhowardpdx would you like to get a PR contribution for that enhancement?

**Comment by kenhowardpdx** [comment]
A PR is very much welcomed @mlewand.

**Comment by Logerfo** [comment]
I don't think this is needed anymore since now VSCode has this feature implemented natively.

**Comment by mlewand** [comment]
@Logerfo that's right, I even didn't notice when I started using this feature.

For anyone looking how to do this, just right click the status bar and pick an option that should be hidden.

![image](https://user-images.githubusercontent.com/5353898/65962614-5d4c1400-e459-11e9-90c5-5c36b0a22e51.png)

@kenhowardpdx I believe that indeed it might be closed.

**Comment by kenhowardpdx** [comment]
Thanks everyone. I guess I should use VS Code some more. :)
