### ISSUE TITLE
Auth not saved

### ISSUE THREAD

**Issue by AntonGrekov** [kenhowardpdx/vscode-gist#47]
Why extension always ask for a username and password or auth token. Entering it correctly once doesnt solve problem. This is very uncomfortable

**Comment by kenhowardpdx** [comment]
Hi @AntonGrekov. Do you have any other extensions installed? Which version of vscode-gist do you have?

**Comment by kenhowardpdx** [comment]
If this is still an issue please re-open and provide more detail.
