### ISSUE TITLE
Insert gist snippet into current document

### ISSUE THREAD

**Issue by kenhowardpdx** [kenhowardpdx/vscode-gist#5]
@Blumed wrote here https://github.com/dbankier/vscode-gist/issues/25
> I am a recent lover of VSC coming from Sublime. I used a gist plugin for a long time. It has a feature of being able to paste the gist you select where ever your cursor is in your current document.

**Comment by robertpetras** [comment]
+1
This feature would be very appreciated. At this time there is no such a VS Code extension for that.

**Comment by kenhowardpdx** [comment]
@Blumed & @robertpetras this feature has been added. Enjoy!
