### ISSUE TITLE
Set filename to (sanitized) description

### ISSUE THREAD

**Issue by mrkafk** [kenhowardpdx/vscode-gist#50]
**This is a**

- [ ] bug report
- [x] feature request

#### Description

I do not want to give away the filename I'm working on, incl. public gists. 

Would it be possible to add an option to:

- use sanitized description like a filename, like "   python: my nice little function    " -> "python_my_nice_little_function"

- nice to have: use current file's extension for the filename, like .py for python file, .js for javascript, etc

Additional benefit is if you download all your gistfiles via Github API (like I do), they have proper names already.

**Comment by kenhowardpdx** [comment]
When adding a file you are now prompted to provide a name. It defaults to the current filename.
