### ISSUE TITLE
Lazy load the extension?

### ISSUE THREAD

**Issue by epeli** [kenhowardpdx/vscode-gist#52]
**This is a**

- [ ] bug report
- [x] feature request

#### Description

I noticed that this extension gets activated on the vscode startup (`"activationEvents": ["*"]` in package.json) which seems little bit weird to me since this is very much a command driven extension.

Why not just lazily activate the extension when one of the registered commands gets called?

Motivation: This is a really useful extension but most days I won't be using it so I would prefer it to not have the extension host process running all the time.

**Comment by kenhowardpdx** [comment]
Thanks for your request. Unfortunately most of the use case around this extension is to quickly access and create Gists. Knowing what profile you are using is essential to creating the Gists. This needs to be activated at startup.
