### ISSUE TITLE
Authentication doesn't support 2FA

### ISSUE THREAD

**Issue by kenhowardpdx** [kenhowardpdx/vscode-gist#6]
@jcam3ron wrote here https://github.com/dbankier/vscode-gist/issues/26
> Hi, I have 2FA enabled on my Github account and cannot login with this plugin as it doesn't seem to support it.

> See https://developer.github.com/v3/auth/#working-with-two-factor-authentication for details

**Comment by robertpetras** [comment]
Okay, so we can not use this great extension with GH's 2 factor authentication unfortunately. :-0

**Comment by MatthieuScarset** [comment]
@robertpetras nope, we CAN use this extension with GH 2FA.

You need to create a Personal Token and add it to your VS settings:
`"gist.oauth_token": "xxxxxxxxxxxxxx"`

**Comment by kenhowardpdx** [comment]
I will be looking at 2FA in a future release... but as for now you'll need to use the personal access token.

**Comment by shadowmaru** [comment]
I actually prefer using Personal Tokens instead of typing my Github password :)

**Comment by kenhowardpdx** [comment]
@shadowmaru I'm leaning toward prompting users to enter personal access token OR username/password. The underlying code generates a token upon successful login. If you login from multiple machines you end up with multiple personal access tokens which can be confusing when reviewing your personal access tokens.

**Comment by kenhowardpdx** [comment]
FYI, you can now log in w/ a personal access token. https://github.com/kenhowardpdx/vscode-gist/compare/v1.1.5...v1.2.0

Closing for now.

**Comment by Kamshak** [comment]
How to do this? It only asks me for password :( using gist.oauth_token in user settings didnt work either

**Comment by kenhowardpdx** [comment]
@Kamshak thanks for letting me know `gist.oauth_token` doesn't work. That is a bug that I'll need to fix.

**Here are the steps for setting the token in the UI:**

1. press `F1` on your keyboard to open the command pallette
2. filter for `GIST: Open Block` and press enter on your keyboard when selected
3. when prompted for a username press enter without entering a value
4. you'll be prompted for a personal access token
5. enter personal access token and press enter on your keyboard

**Comment by Kamshak** [comment]
Thanks for the explanation! :)
I've just tried again and when selecting the gist.oauth_token from the setting list instead of copying it in it does work. Not entirely sure what went wrong the first time but it was probably something i did. 

Thanks for the great addon!
