### ISSUE TITLE
Github Enterprise and HTTPS certs

### ISSUE THREAD

**Issue by mrkafk** [kenhowardpdx/vscode-gist#83]
**This is a**
- [x] bug report
- [ ] feature request

#### Description

VSCode: 1.28.2
Extension: 2.1.1

I'm using Github Enterprise at the company.

I get this error on trying to dl gists:

```
GIST ERROR: Could Not Insert > Reason: request to https://github.example.com/api/v3/gists?per_page=9999 failed, reason: unable to verify the first certificate
```

Our Github Enterprise instance is NOT behind HTTPS proxy. I still set it like this: https://stackoverflow.com/questions/36506539/how-do-i-get-visual-studio-code-to-trust-our-self-signed-proxy-certificate 

Predictably, this has not helped.

Unfortunately let's just say that there is no way to get our GHE to get proper certificates installed. 

Obviously, this may be the core VSCode issue and not the one in your extension. If there's no way to fix this on your side, pls let me know, I'll open bug report at main VSCode repo.

**Comment by kenhowardpdx** [comment]
I’ll investigate.

**Comment by mrkafk** [comment]
Any update please?

**Comment by mrkafk** [comment]
This, ahem, solution, has worked:

https://stackoverflow.com/questions/33820733/error-unable-to-verify-the-first-certificate-how-to-trust-all-certificates

But I'm not really happy with it, because obviously it makes VSCode trust ALL the certificates...

**Comment by kenhowardpdx** [comment]
I will investigate further. Thanks for following up and linking to the vscode issue.

**Comment by kenhowardpdx** [comment]
https://nodejs.org/api/https.html#https_https_request_options_callback
