### ISSUE TITLE
BUG: Can't type closing curly brace because of the ctrl+alt+0 shortcut on German keyboard layout

### ISSUE THREAD

**Issue by Systemcluster** [kenhowardpdx/vscode-gist#84]
**This is a**
- [x] bug report
- [ ] feature request

#### Description
Since the recent update, `extension.resetState` is bound to `ctrl+alt+0` by default - this clashes with German keyboard layouts, where `AltGr+0` is the closing curly brace `}`. [As `Ctrl+Alt` is an alias for `AltGr` on Windows](https://blogs.msdn.microsoft.com/oldnewthing/20040329-00/?p=40003), this binding makes it impossible to type the closing brace - I was quite puzzled until I figured out what the issue was.

I would suggest changing this default binding to something else, e.g. `Ctrl+Shift+0`.

**Comment by kenhowardpdx** [comment]
Thank you for bringing this to my attention! I had no idea. 😮

**Comment by telekommander** [comment]
Running in the same issue.

Just a Workaround:
Add this to your (global) keybindings.json.
The first entry remap the "resetState" ( my choice ), the second one removes the keymapping coming from the extension.
```    
{
    "command": "extension.resetState",
    "key": "ctrl+shift+alt+0"
},
{
    "key": "ctrl+alt+0",
    "command": "-extension.resetState"
}
```
