### ISSUE TITLE
BUG - save the opened gist does not update it

### ISSUE THREAD

**Issue by hyphaene** [kenhowardpdx/vscode-gist#9]
**This is a**
- [x] bug report

#### Description
Hi, 
I'm on vscode 1.15.1
the extension is on : 1.1.2

the bug is in the title.
=> I create a gist.
=> I open it through the command GIST:open block
=> the file is displayed from /tmp/vscode/<some hash>
=> when I save the file, nothing happens.

Cheers.

**Comment by kenhowardpdx** [comment]
Thanks for the bug report @hyphaene! I've published the fix.

**Comment by hyphaene** [comment]
No problem of course, and thank you for the reactivity!
